version: '2'
services:
  bookerinventory-mongodb:
    image: mongo:4.0.12
    ports:
      - '27017:27017'
    command: mongos --configdb bookerinventory-mongodb-config
  bookerinventory-mongodb-node:
    build:
      context: .
      dockerfile: mongodb/MongoDB.Dockerfile
    command: mongod --replSet rs1 --noprealloc --smallfiles
  bookerinventory-mongodb-config:
    image: mongo:4.0.12
    container_name: bookerinventory-mongodb-config
    command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
